services:
  - type: web
    name: voice-chat-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true